version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "SEG2505_Project/build.gradle" }}-{{ checksum  "SEG2505_Project/app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: | 
            cd SEG2505_Project
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "SEG2505_Project/build.gradle" }}-{{ checksum  "SEG2505_Project/app/build.gradle" }}
      - run:
          name: Run Tests
          command: | 
            cd SEG2505_Project
            ./gradlew test
      - store_artifacts: 
          path: app/build/outputs/apk/debug
          destination: apks/
      - store_test_results: 
          path: app/build/test-results
      - run:
          name: The Last Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      

